### ISSUE TITLE
Readme points to incorrect location for the git clone

### ISSUE THREAD

**Issue by sudhir-intc** [free5gc/free5gc-stage-3#4]
The readme at https://github.com/free5gc/free5gc-stage-3/blob/master/readme.md for clone points to the incorrect location "git clone https://bitbucket.org/free5GC/free5gc-stage-2.git free5gc" 
This needs to be corrected to "git clone https://github.com/free5gc/free5gc-stage-3.git"

**Comment by free5gc-org** [comment]
Hi,
Thanks for your revise, we will fix it recently.

Many Thanks

**Comment by free5gc-org** [comment]
Hi,

Thanks again for helping us to fix the document. We have fix it and update to free5ge/free5gc repository.
We'll archive this repository (free5gc-stage-3) form now and update all our change in free5gc/free5gc in the future.
